//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nmfs.Agepro.Gui.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AgeproStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AgeproStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nmfs.Agepro.Gui.Resources.AgeproStrings", typeof(AgeproStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.25.
        /// </summary>
        internal static string AGEPRO_Version {
            get {
                return ResourceManager.GetString("AGEPRO_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraction Mortality Prior to Spawning.
        /// </summary>
        internal static string Bio_TSpawn_TextLabel {
            get {
                return ResourceManager.GetString("Bio_TSpawn_TextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CalcEnginePath {
            get {
                return ResourceManager.GetString("CalcEnginePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.25-4.3.4.
        /// </summary>
        internal static string GUI_Version {
            get {
                return ResourceManager.GetString("GUI_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGEPRO VERSION 4.25.
        /// </summary>
        internal static string INPVersionString {
            get {
                return ResourceManager.GetString("INPVersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGEPRO.
        /// </summary>
        internal static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
    }
}
